version: "3.7"

services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres:13.1-alpine
    env_file:
      - local.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

#  pgadmin:
#    image: dpage/pgadmin4:4.28
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: 'v@home.com'
#      PGADMIN_DEFAULT_PASSWORD: secret
#      PGADMIN_LISTEN_PORT: 8080
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./pgadmin-data:/var/lib/pgadmin
#    links:
#      - "postgres:pgsql-server"