# Generated by Django 3.1.3 on 2020-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(unique=True)),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('sender', models.TextField()),
                ('message', models.TextField()),
                ('tag', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'donations',
            },
        ),
    ]
