# Generated by Django 3.1.3 on 2020-12-07 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs', '0002_donation_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregateSlug',
            fields=[
                ('slug', models.CharField(max_length=16, primary_key=True, serialize=False, unique=True)),
                ('tags', models.TextField()),
            ],
            options={
                'db_table': 'aggregate_slugs',
            },
        ),
    ]
